evaluation:
  evaluate_after: -1
  every_eval: 1
  print_every: 100
logging:
  print_level: DEBUG
  write_level: INFO
misc:
  dataset: charades
  debug: false
  exp_prefix: charades/language_free
  method_type: tgn_lgi
  num_workers: 4
  print_every: 100
  result_dir: results/charades/language_free
  tensorboard_dir: tensorboard/charades/language_free
  vis_every: 0
  seed: 0
model:
  noise_level: 0.5
  sigma: 2
  gamma: 0.2
  tag_weight: 1.
  num_proposals: 1
  learned_noise: true
  l1_threshold: 0.3
  att_div_alpha: 1
  att_div_lambda: 0.8
  l1_alpha: 1.
  nce_tau: 0.25
  nce_alpha: 1
  proposal_nce_alpha: 1
  intra_nce_alpha: 1
  intra_margin_1: 0.4
  intra_margin_2: 0.5
  use_clip_mask: false
  checkpoint_path: ''
  dqa_lambda: 0.3
  dqa_weight: 1.0
  glove_path: ''
  grounding_att_cand_dim: 512
  grounding_att_drop_prob: 0.0
  grounding_att_hdim: 256
  grounding_att_key_dim: 512
  grounding_hdim: 512
  grounding_idim: 512
  lgi_fusion_method: mul
  lgi_global_nl_drop_prob: 0.0
  lgi_global_nl_idim: 512
  lgi_global_nl_nheads: 1
  lgi_global_nl_odim: 512
  lgi_global_nl_use_bias: true
  lgi_global_nl_use_local_mask: false
  lgi_global_num_nl_block: 1
  lgi_global_satt_att_cand_dim: 512
  lgi_global_satt_att_edim: -1
  lgi_global_satt_att_hdim: 256
  lgi_global_satt_att_n: 1
  lgi_global_satt_att_use_embedding: false
  lgi_global_type: nl
  lgi_hp_hdim: 512
  lgi_hp_idim_1: 512
  lgi_hp_idim_2: 512
  lgi_local_do_downsample: false
  lgi_local_num_res_blocks: 1
  lgi_local_res_block_1d_hdim: 256
  lgi_local_res_block_1d_idim: 512
  lgi_local_res_block_1d_ksize: 15
  lgi_local_res_block_1d_odim: 512
  lgi_local_type: res_block
  loc_word_emb_vocab_size: 1140
  model_type: LGI
  num_semantic_entity: 1
  query_enc_emb_idim: 1140
  query_enc_emb_odim: 300
  query_enc_rnn_bidirectional: true
  query_enc_rnn_dropout: 0.5
  query_enc_rnn_hdim: 256
  query_enc_rnn_idim: 300
  query_enc_rnn_nlayer: 2
  query_enc_rnn_type: LSTM
  resume: false
  sqan_att_cand_dim: 512
  sqan_att_drop_prob: 0.0
  sqan_att_hdim: 256
  sqan_att_key_dim: 512
  sqan_qdim: 512
  use_negative_proposal: true
  use_attention_div: false
  use_gpu: true
  use_temporal_attention_guidance_loss: true
  use_video_encoder: false
  use_l1_loss: true
  use_nce_loss: true
  use_proposal_nce: false
  use_multi_tag: false
  video_enc_pemb_idim: 200
  video_enc_pemb_odim: 512
  video_enc_use_position: true
  video_enc_vemb_idim: 1024
  video_enc_vemb_odim: 512
  sentence_emb_dim: 512
  dataset: charades
  num_cross_layers: 3
  emb_cross_dim: 512
  num_head: 4
  kernel_size: 3
  padding: 1
  num_self_layers: 2
optimize:
  decay_factor: 0.5
  decay_step: -1
  init_lr: 0.0004
  num_step: 1500
  optimizer_type: Adam
  scheduler_type: ''
test_loader:
  batch_size: 128
  data_dir: data/charades
  dataset: charades
  feature_type: I3D
  in_memory: true
  max_length: 10
  num_segment: 200
  split: test
  sample_num: 10
  video_feature_path: data/charades/i3d_features.hdf5
  anno_path: data/charades/pseudo/charades_test_original.json
  clip_video_feature_path: data/charades/charades_clip_video.h5
  clip_text_feature_path: data/charades/charades_clip_text.h5
  word_frequency_threshold: 1
train_loader:
  batch_size: 128
  data_dir: data/charades
  dataset: charades
  feature_type: I3D
  in_memory: true
  max_length: 10
  num_segment: 200
  split: train
  sample_num: 10
  video_feature_path: data/charades/i3d_features.hdf5
  clip_video_feature_path: data/charades/charades_clip_video.h5
  anno_path: data/charades/pseudo/charades_train_pseudo_unique.json
  sentences_corpus_feat_path: data/charades/charades_corpus_feat.npy
  use_corpus: true
  word_frequency_threshold: 1
